const settings = {
  packname: 'Evil Imranos Bot',
  author: 'Imrane Moussaid',
  botName: 'Evil Imranos Bot',
  botOwner: 'Imrane Moussaid',
  ownerNumber: '212617503205',
  ownerNumbers: ['212617503205', '212607361454'],
  devNumbers: ['212617503205', '212607361454'],
  commandPrefix: '.',
  newsletterJid: '120363269950668068@newsletter',
  telegramHandlersDir: 'handlers',
  premiumDbPath: 'data/premium_users.db',
  channelUrl: 'https://whatsapp.com/channel/0029VZzc5wUKrWQraNl2Li2b',
  youtubeUrl: 'https://youtube.com/@Godszealtech',
  giphyApiKey: 'qnl7ssQChTdPjsKta2Ax2LMaGXz303tq',
  commandMode: 'public',
  maxStoreMessages: 20,
  storeWriteInterval: 10000,
  description: 'This is a bot for managing group commands and automating tasks.',
  version: '3.1.0',
  updateZipUrl: 'https://github.com/AiOfLautech/God-s-zeal-Xmd/archive/refs/heads/main.zip',
  pairApiBase: process.env.PAIR_API_BASE || '',
  mongoUri: process.env.MONGO_URI || '',
  mongoDbName: process.env.MONGO_DB_NAME || 'gods_zeal_xmd',
  mongoEncryptionKey: process.env.MONGO_ENCRYPTION_KEY || '',
};

module.exports = settings;
